lesson-4-homework
avpeshkov/my-react-js-tutorial pull request #4
Opened 2020-11-08 15:20 UTC by avpeshkov

2020-11-09 08:29 UTC, Fedos2589 requested changes

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/MoodForm/MoodForm.tsx
> +    onDateUpdate = (currentDate: Date): void => {
если стрелка только возвращает что-либо без дополнительных действий, то можно в 1 строку
onDateUpdate = (currentDate: Date): void => this.setState({ date: currentDate });

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/MoodForm/MoodForm.tsx
> +                <MoodScale currentMood={mood} onMoodUpdate={isViewMode ? undefined : this.onMoodUpdate} />
флагом было бы короче
isViewMode && this.onMoodUpdate

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/MoodHistory/MoodHistory.tsx
> +                    <MoodForm isViewMode={true} moodObject={item} key={index} />
index в key это антипаттерн, лучше чтото другое взять, уникальное, например если я правильно понял у нас никогда не будет 2 настроения с одинаковой датой, а значит можно развернуть дату для key

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/MoodHistory/MoodHistory.tsx
> +                <QuoteBlock interval={10000} isAutoSwitchEnabled={true} />
магические числа лучше в константу выносить

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/MoodScale/MoodScale.tsx
> +                    <MoodItem key={mood} mood={mood} isFilled={mood <= currentMood} onClick={onMoodUpdate ? () => onMoodUpdate(mood) : undefined} />
тут я бы тоже на флаг переписал

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/QuoteBlock/QuoteBlock.tsx
> +                <QuoteButton onClick={this.setQuote.bind(this, "previous")}>{"<"}</QuoteButton>
bind в рендере не надо делать, либо в конструктор либо стрелочной функцией пишем метод

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/QuoteBlock/QuoteBlock.tsx
> +                <QuoteButton onClick={this.setQuote.bind(this, "next")}>{">"}</QuoteButton>
bind

2020-11-09 08:29 UTC, Fedos2589 commented on src/components/utils.tsx
> +export const getRandomIndex = (arrayLength: number): number => {
тут тоже можно стрелку в строку

2020-11-09 16:41 UTC, avpeshkov commented on src/components/MoodForm/MoodForm.tsx
> +                <MoodScale currentMood={mood} onMoodUpdate={isViewMode ? undefined : this.onMoodUpdate} />
вообще по тайпскрипту не очень сходится, тк isViewMode может быть false, а такое значение аргумент ожидающий функцию или undefinde получить не может, можно коненчно переписать через дополнительную переменную, но зачем)

2020-11-09 16:51 UTC, avpeshkov commented on src/components/QuoteBlock/QuoteBlock.tsx
> +                <QuoteButton onClick={this.setQuote.bind(this, "previous")}>{"<"}</QuoteButton>
а можно пожалустай пояснить почему, хочу разобраться, на работе у нас такое часто делается?

2020-11-10 10:57 UTC, merged

2021-02-06 10:02 UTC, nickovchinnikov commented on src/components/MoodHistory/MoodHistory.tsx
> +    constructor(props: {}) {
Просто напомню, что в проекте подключен
https://www.npmjs.com/package/babel-plugin-transform-class-properties

2021-02-06 10:04 UTC, nickovchinnikov commented on src/components/QuoteBlock/QuoteBlock.tsx
> +    constructor(props: QuoteBlockProps) {
На всякий случай продублирую)
https://www.npmjs.com/package/babel-plugin-transform-class-properties

2021-02-06 10:05 UTC, nickovchinnikov commented on src/components/QuoteBlock/QuoteBlock.tsx
> +        this._isMounted = false;
Посмотрел  `this._isMounted` и кажется, если убрать этот флаг, ничего не изменится

2021-02-06 10:07 UTC, nickovchinnikov commented on src/components/QuoteBlock/QuoteBlock.tsx
> +    setRandomQuote() {
Так как мы вызываем эту функцию внутри `componentDidMount + componentDidUpdate` предполагаю `this._isMounted` можно выпилить

2021-02-06 10:10 UTC, nickovchinnikov commented on src/components/QuoteBlock/QuoteBlock.tsx
> +        switch (position) {
Если position is binary
`position == "next" ? newId++ : newId--`