[ft/lesson-12-homework]
avpeshkov/my-react-js-tutorial pull request #9
Opened 2020-12-10 17:10 UTC by avpeshkov

Добавлен роутер, добавлены страницы, добавлена авторизация, переезд на firebase c json server

2020-12-23 19:22 UTC, AntiHero requested changes

2020-12-23 19:22 UTC, AntiHero commented on package.json
> +    "json-server": "npx json-server --port 3001 --watch db.json",
npx для установленных модулей писать не надо, вроде обсуждали с тобой этот момент раньше

2020-12-23 19:50 UTC, AntiHero commented on src/api/mood.ts
> +/**
вроде ты JSDoc писал, почему решил делать такие комментарии?

2020-12-23 20:10 UTC, AntiHero commented on src/api/mood.ts
> + *   Апдейтим/Создаем записи настроения настроения
видно копировал комментарии, в связи с этим повторы, если даёшь понятные имена функциям нет смысла добавлять комментарии такого рода

2020-12-23 20:16 UTC, AntiHero commented on src/services/firebase.ts
> +    auth: firebase.auth ? firebase.auth : authMock,
не совсем нравится мне эта штука, зачем тесты (неважно в каком объёме) привносить в основной функционал, который у тебя деплоится? разве нельзя замокать твой firebase.auth исключительно для тестов, чтобы мок использовался во время их прогона?

2020-12-23 20:22 UTC, AntiHero commented on jest.config.js
> +        "^pages(.*)$": "<rootDir>/src/pages$1",
кстати, почему решил логин и т.д. добавить в папку pages а не в components? pages к слову в nextjs используется, это конечно не страшно, но в любом случае лучше придёрживаться определённой структуры проекта

2020-12-23 20:26 UTC, AntiHero commented
и formik ты установил, но решил не использовать?

2021-01-08 14:46 UTC, avpeshkov commented on src/services/firebase.ts
> +    auth: firebase.auth ? firebase.auth : authMock,
мне тоже не нравится, но на практике, выходит что что бы замокать firebase.auth для тестов нужно сделать так, просто так выходит что прежде чем мокнутся он пытается заинициализироватся, в тестах нет пееременных конфига, и как следствие все падает -_-.
хотел потом переписать эту тему в каком нить другом виде, но пул реквест и так гиганский вышел.

2021-01-08 14:48 UTC, avpeshkov commented on jest.config.js
> +        "^pages(.*)$": "<rootDir>/src/pages$1",
логин и т.д ну так логин и тд это же отдельные страницы, у них есть урлы в ройтере, разве они должны быть не в pages?

2021-01-08 14:49 UTC, avpeshkov commented
> и formik ты установил, но решил не использовать?

почему, он используется в форме для редактирования записи настроения, просто в рамках экспериментов с antd решил попробовать использовать их формы.

2021-01-08 18:19 UTC, AntiHero commented on src/services/firebase.ts
> +    auth: firebase.auth ? firebase.auth : authMock,
в тестах можно использовать переменные конфига + можно попробовать использовать свой  [setupTests.js](https://create-react-app.dev/docs/running-tests/) файл, в котором можно делать нужные тебе вещи

2021-01-08 18:26 UTC, AntiHero commented on jest.config.js
> +        "^pages(.*)$": "<rootDir>/src/pages$1",
это прежде всего компоненты, как мне кажется, в любом случае это не критичный момент, один из хороших по-моему мнению материалов по поводу структуры реакт приложений [ссылка](https://charles-stover.medium.com/optimal-file-structure-for-react-applications-f3e35ad0a145)

2021-01-08 18:35 UTC, avpeshkov commented on src/services/firebase.ts
> +    auth: firebase.auth ? firebase.auth : authMock,
я возможно чего-то не до конца понимаю?
я к тому что я же не могу деплоить реальные переменные конфига, а если я подставлю любые другие, то во время инициализации firbase  произойдет ошибка, чем мне тут поможет jestSettings ?

2021-01-08 18:40 UTC, AntiHero commented
по поводу ошибки  ```console.error ...
      Warning: An update to Formik inside a test was not wrapped in act(...).```
 посмотри пожалуйста [help](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning)

2021-01-08 18:51 UTC, AntiHero commented on package.json
> +    "start": "env-cmd -f .env webpack-dev-server --mode development --open --hot",
env-cmd глобально установил?)

2021-01-08 19:03 UTC, AntiHero commented on src/services/firebase.ts
> +    auth: firebase.auth ? firebase.auth : authMock,
а где ты деплоишь (собираешься деплоить) переменные конфига?

2021-01-08 19:04 UTC, avpeshkov commented on package.json
> +    "start": "env-cmd -f .env webpack-dev-server --mode development --open --hot",
да, он у меня собственное и так стоял глобально для других проектов, но можно и прописать  в зависимости

2021-01-09 20:10 UTC, merged